version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    command: >
      --model mistralai/Mistral-7B-Instruct-v0.3
      --dtype auto
      --enable-prefix-caching
      --gpu-memory-utilization 0.85
      --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  fastapi:
    build: ./inference
    ports:
      - "8001:8001"
    depends_on:
      - vllm
    environment:
      VLLM_API_URL: http://vllm:8000/v1
      MODEL_NAME: mistralai/Mistral-7B-Instruct-v0.3
      OPENAI_API_KEY: token-what-a-day
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
