version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    command: >
      --model TheBloke/Mistral-7B-v0.1-AWQ
      --chat-template mistral
      --dtype auto
      --enable-prefix-caching
      --gpu-memory-utilization 0.90
      --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  fastapi:
    build: ./inference
    ports:
      - "8001:8001"
    depends_on:
      - vllm
    environment:
      VLLM_API_URL: http://vllm:8000/v1
      MODEL_NAME: TheBloke/Mistral-7B-v0.1-AWQ
      OPENAI_API_KEY: token-what-a-day
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
