version: '3.8'

services:
  vllm:
    image: ollama/ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      bash -c "
        ollama serve &
        echo 'Waiting for Ollama server...'
        sleep 6
        ollama pull adrienbrault/nous-hermes2theta-llama3-8b:q5_K_M

        wait
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  fastapi:
    build: ./inference
    ports:
      - "8001:8001"
    depends_on:
      - vllm
    environment:
      VLLM_API_URL: http://vllm:11434
      MODEL_NAME: adrienbrault/nous-hermes2theta-llama3-8b:q5_K_M
      OPENAI_API_KEY: token-what-a-day
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_data:  # Define the volume here